version: '3'

services:
  xzy-tunnel:
    build:
      context: .  # 指向包含Dockerfile的目录
    container_name: xzy-tunnel-server
    restart: always
    ports:
      - "${PORT:-1234}:1234"  # 外部端口可配置，内部端口保持固定为1234
    environment:
      - NODE_ENV=production
      - PORT=1234  # 容器内部端口固定为1234
      - LOG_LEVEL=info
      - DEFAULT_TARGET_PORT=80
      - BLOCKED_PORTS=25,465,587
      - TUNNEL_HEADER_NAME=xzytunnel
      - ENABLE_CORS=true
      - REQUEST_TIMEOUT=30000
      - LOG_REQUEST_HEADERS=false
      - LOG_REQUEST_BODY=false
      - PRESERVE_HOST_HEADER=false
    volumes:
      - ./logs:/app/logs
    networks:
      - xzy_network

networks:
  xzy_network:
    driver: bridge